/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StatisticsCalculator */

#ifndef _Included_StatisticsCalculator
#define _Included_StatisticsCalculator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
